import Head from 'next/head'
import {Buttons} from 'src/components'

export default function Home() {
    return <>
        <Head>
            <title>Jildert v Baal</title>
            <meta name='description' content='Generated by create next app'/>
            <meta name='viewport' content='width=device-width, initial-scale=1'/>
            <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
            <Buttons.Link href={'/je-moeder'}>
                DEMO!
            </Buttons.Link>
        </main>
    </>
}
